apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-strapi-helm
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  type: ClusterIP
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "strapi.fullname" . }}
          servicePort: 1337
