apiVersion: v1
kind: Service
metadata:
  name: {{ template "strapi.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  ports:
  - port: {{ default 1337 .Values.service.externalPort }}
    targetPort: {{ default 1337 .Values.service.internalPort }}
    protocol: TCP
  selector:
    app: {{ template "strapi.fullname" . }}